[package]
name = "day_05_part_02_v2"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = { workspace = true }

[dev-dependencies]
divan = { workspace = true }

[[bench]]
name = "benchmark"
harness = false

[lib]
doctest = false
